FROM mysql:mysql:5.7.28
LABEL Maintainer="Sean Wu <wuxyyin@qq.com>" \
      Description="Mysql 5.7.28 container with Closed ONLY_FULL_GROUP_BY in sql_mode."

COPY conf.d/wuxyyin.cnf /etc/mysql/conf.d/wuxyyin.cnf
